# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradeList',
            new_name='PurchaseList',
        ),
    ]
